sonar.projectKey=sla-rbt-app
sonar.projectName=SLA RBT App
sonar.projectVersion=1.0

# Path to the source code
sonar.sources=src
sonar.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/setupTests.ts,node_modules/**

# Path to the tests
sonar.tests=src
sonar.test.inclusions=src/**/*.test.tsx,src/**/*.test.ts

# Code Coverage (jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.tsx,src/**/*.test.ts,src/setupTests.ts,src/index.tsx,src/react-app-env.d.ts,src/types/**

# Encoding
sonar.sourceEncoding=UTF-8
